some account to object views
siriuscollegedevs/bft pull request #35
Opened 2023-07-19 10:53 UTC by annashutova

2023-07-20 07:07 UTC, KatyaGotskina requested changes

2023-07-20 07:07 UTC, KatyaGotskina commented on backend/sirius/sirius_access/models.py
> +    def get_last_version(self):
Переименована функция, однако не изменены views, в которых используется старое название

2023-07-20 07:40 UTC, DanielUsov commented on backend/sirius/sirius/general_functions.py
> +def get_account(request) -> Account:
При `get_account` происходит ошибка миграций, при `get_user` все ок

2023-07-25 15:03 UTC, KatyaGotskina approved these changes

2023-07-25 15:03 UTC, merged